/**
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.junit.runner.RunWith;
import org.polarsys.chess.iot.tests.Model;
import org.polarsys.chess.iot.tests.RuntimeDslInjectorProvider;

@RunWith(XtextRunner.class)
@InjectWith(RuntimeDslInjectorProvider.class)
@SuppressWarnings("all")
public class RuntimeDslParsingTest {
  @Inject
  public void eResource(final Model model) {
    throw new UnsupportedOperationException("TODO: auto-generated method stub");
  }
}
