/**
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.ui.contentassist;

import org.polarsys.chess.iot.ui.contentassist.AbstractRuntimeDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RuntimeDslProposalProvider extends AbstractRuntimeDslProposalProvider {
}
