/*
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FlaDslStandaloneSetup extends FlaDslStandaloneSetupGenerated {

	def static void doSetup() {
		new FlaDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
