/**
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot;

import org.polarsys.chess.iot.RuntimeDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RuntimeDslStandaloneSetup extends RuntimeDslStandaloneSetupGenerated {
  public static void doSetup() {
    new RuntimeDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
