/**
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.validation;

import org.polarsys.chess.iot.validation.AbstractRuntimeDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RuntimeDslValidator extends AbstractRuntimeDslValidator {
}
