/*
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.polarsys.chess.iot.ide.contentassist.antlr.internal.InternalRuntimeDslParser;
import org.polarsys.chess.iot.services.RuntimeDslGrammarAccess;

public class RuntimeDslParser extends AbstractContentAssistParser {

	@Inject
	private RuntimeDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalRuntimeDslParser createParser() {
		InternalRuntimeDslParser result = new InternalRuntimeDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModuleAccess().getAlternatives_5(), "rule__Module__Alternatives_5");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getModuleAccess().getGroup(), "rule__Module__Group__0");
					put(grammarAccess.getStartAccess().getGroup(), "rule__Start__Group__0");
					put(grammarAccess.getStopAccess().getGroup(), "rule__Stop__Group__0");
					put(grammarAccess.getRestartAccess().getGroup(), "rule__Restart__Group__0");
					put(grammarAccess.getRedeployAccess().getGroup(), "rule__Redeploy__Group__0");
					put(grammarAccess.getLogAccess().getGroup(), "rule__Log__Group__0");
					put(grammarAccess.getMonitorAccess().getGroup(), "rule__Monitor__Group__0");
					put(grammarAccess.getRunAccess().getGroup(), "rule__Run__Group__0");
					put(grammarAccess.getUsesAccess().getGroup(), "rule__Uses__Group__0");
					put(grammarAccess.getModelAccess().getNameAssignment_1(), "rule__Model__NameAssignment_1");
					put(grammarAccess.getModelAccess().getModuleAssignment_2(), "rule__Model__ModuleAssignment_2");
					put(grammarAccess.getModuleAccess().getNameAssignment_2(), "rule__Module__NameAssignment_2");
					put(grammarAccess.getModuleAccess().getUsesAssignment_3(), "rule__Module__UsesAssignment_3");
					put(grammarAccess.getModuleAccess().getActionAssignment_5_0(), "rule__Module__ActionAssignment_5_0");
					put(grammarAccess.getModuleAccess().getActionAssignment_5_1(), "rule__Module__ActionAssignment_5_1");
					put(grammarAccess.getModuleAccess().getActionAssignment_5_2(), "rule__Module__ActionAssignment_5_2");
					put(grammarAccess.getModuleAccess().getActionAssignment_5_3(), "rule__Module__ActionAssignment_5_3");
					put(grammarAccess.getModuleAccess().getActionAssignment_5_4(), "rule__Module__ActionAssignment_5_4");
					put(grammarAccess.getModuleAccess().getActionAssignment_5_5(), "rule__Module__ActionAssignment_5_5");
					put(grammarAccess.getModuleAccess().getActionAssignment_5_6(), "rule__Module__ActionAssignment_5_6");
					put(grammarAccess.getStartAccess().getNameAssignment_1(), "rule__Start__NameAssignment_1");
					put(grammarAccess.getStopAccess().getNameAssignment_1(), "rule__Stop__NameAssignment_1");
					put(grammarAccess.getRestartAccess().getNameAssignment_1(), "rule__Restart__NameAssignment_1");
					put(grammarAccess.getRedeployAccess().getNameAssignment_1(), "rule__Redeploy__NameAssignment_1");
					put(grammarAccess.getLogAccess().getNameAssignment_1(), "rule__Log__NameAssignment_1");
					put(grammarAccess.getMonitorAccess().getNameAssignment_1(), "rule__Monitor__NameAssignment_1");
					put(grammarAccess.getMonitorAccess().getValueAssignment_3(), "rule__Monitor__ValueAssignment_3");
					put(grammarAccess.getRunAccess().getModuleAssignment_1(), "rule__Run__ModuleAssignment_1");
					put(grammarAccess.getUsesAccess().getModuleAssignment_1(), "rule__Uses__ModuleAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public RuntimeDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RuntimeDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
