/**
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot;

import org.polarsys.chess.iot.AbstractRuntimeDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RuntimeDslRuntimeModule extends AbstractRuntimeDslRuntimeModule {
}
