/*
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractRuntimeDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage.eINSTANCE);
		return result;
	}
	
}
