/**
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.runtimeDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.polarsys.chess.iot.runtimeDsl.Expression#getName <em>Name</em>}</li>
 *   <li>{@link org.polarsys.chess.iot.runtimeDsl.Expression#getSetup <em>Setup</em>}</li>
 *   <li>{@link org.polarsys.chess.iot.runtimeDsl.Expression#getPlan <em>Plan</em>}</li>
 *   <li>{@link org.polarsys.chess.iot.runtimeDsl.Expression#getDescription <em>Description</em>}</li>
 *   <li>{@link org.polarsys.chess.iot.runtimeDsl.Expression#getAgent <em>Agent</em>}</li>
 * </ul>
 *
 * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getExpression_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.polarsys.chess.iot.runtimeDsl.Expression#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Setup</b></em>' attribute.
   * The literals are from the enumeration {@link org.polarsys.chess.iot.runtimeDsl.BOOLEAN}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Setup</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Setup</em>' attribute.
   * @see org.polarsys.chess.iot.runtimeDsl.BOOLEAN
   * @see #setSetup(BOOLEAN)
   * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getExpression_Setup()
   * @model
   * @generated
   */
  BOOLEAN getSetup();

  /**
   * Sets the value of the '{@link org.polarsys.chess.iot.runtimeDsl.Expression#getSetup <em>Setup</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Setup</em>' attribute.
   * @see org.polarsys.chess.iot.runtimeDsl.BOOLEAN
   * @see #getSetup()
   * @generated
   */
  void setSetup(BOOLEAN value);

  /**
   * Returns the value of the '<em><b>Plan</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Plan</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plan</em>' reference.
   * @see #setPlan(Expression)
   * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getExpression_Plan()
   * @model
   * @generated
   */
  Expression getPlan();

  /**
   * Sets the value of the '{@link org.polarsys.chess.iot.runtimeDsl.Expression#getPlan <em>Plan</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plan</em>' reference.
   * @see #getPlan()
   * @generated
   */
  void setPlan(Expression value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getExpression_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.polarsys.chess.iot.runtimeDsl.Expression#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Agent</b></em>' containment reference list.
   * The list contents are of type {@link org.polarsys.chess.iot.runtimeDsl.AbstractAgent}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Agent</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Agent</em>' containment reference list.
   * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getExpression_Agent()
   * @model containment="true"
   * @generated
   */
  EList<AbstractAgent> getAgent();

} // Expression
