/**
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.runtimeDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>log</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.polarsys.chess.iot.runtimeDsl.log#getService_name <em>Service name</em>}</li>
 *   <li>{@link org.polarsys.chess.iot.runtimeDsl.log#getLog_type <em>Log type</em>}</li>
 *   <li>{@link org.polarsys.chess.iot.runtimeDsl.log#getFilename <em>Filename</em>}</li>
 *   <li>{@link org.polarsys.chess.iot.runtimeDsl.log#getLocation <em>Location</em>}</li>
 *   <li>{@link org.polarsys.chess.iot.runtimeDsl.log#getMachine_name <em>Machine name</em>}</li>
 * </ul>
 *
 * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getlog()
 * @model
 * @generated
 */
public interface log extends rule
{
  /**
   * Returns the value of the '<em><b>Service name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Service name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Service name</em>' attribute.
   * @see #setService_name(String)
   * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getlog_Service_name()
   * @model
   * @generated
   */
  String getService_name();

  /**
   * Sets the value of the '{@link org.polarsys.chess.iot.runtimeDsl.log#getService_name <em>Service name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Service name</em>' attribute.
   * @see #getService_name()
   * @generated
   */
  void setService_name(String value);

  /**
   * Returns the value of the '<em><b>Log type</b></em>' attribute.
   * The literals are from the enumeration {@link org.polarsys.chess.iot.runtimeDsl.LogType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Log type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Log type</em>' attribute.
   * @see org.polarsys.chess.iot.runtimeDsl.LogType
   * @see #setLog_type(LogType)
   * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getlog_Log_type()
   * @model
   * @generated
   */
  LogType getLog_type();

  /**
   * Sets the value of the '{@link org.polarsys.chess.iot.runtimeDsl.log#getLog_type <em>Log type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Log type</em>' attribute.
   * @see org.polarsys.chess.iot.runtimeDsl.LogType
   * @see #getLog_type()
   * @generated
   */
  void setLog_type(LogType value);

  /**
   * Returns the value of the '<em><b>Filename</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Filename</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filename</em>' attribute.
   * @see #setFilename(String)
   * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getlog_Filename()
   * @model
   * @generated
   */
  String getFilename();

  /**
   * Sets the value of the '{@link org.polarsys.chess.iot.runtimeDsl.log#getFilename <em>Filename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filename</em>' attribute.
   * @see #getFilename()
   * @generated
   */
  void setFilename(String value);

  /**
   * Returns the value of the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Location</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Location</em>' attribute.
   * @see #setLocation(String)
   * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getlog_Location()
   * @model
   * @generated
   */
  String getLocation();

  /**
   * Sets the value of the '{@link org.polarsys.chess.iot.runtimeDsl.log#getLocation <em>Location</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Location</em>' attribute.
   * @see #getLocation()
   * @generated
   */
  void setLocation(String value);

  /**
   * Returns the value of the '<em><b>Machine name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Machine name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Machine name</em>' attribute.
   * @see #setMachine_name(String)
   * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getlog_Machine_name()
   * @model
   * @generated
   */
  String getMachine_name();

  /**
   * Sets the value of the '{@link org.polarsys.chess.iot.runtimeDsl.log#getMachine_name <em>Machine name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Machine name</em>' attribute.
   * @see #getMachine_name()
   * @generated
   */
  void setMachine_name(String value);

} // log
