/**
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.runtimeDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>redeploy</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.polarsys.chess.iot.runtimeDsl.redeploy#getService_name <em>Service name</em>}</li>
 *   <li>{@link org.polarsys.chess.iot.runtimeDsl.redeploy#getMachine_address <em>Machine address</em>}</li>
 * </ul>
 *
 * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getredeploy()
 * @model
 * @generated
 */
public interface redeploy extends rule
{
  /**
   * Returns the value of the '<em><b>Service name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Service name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Service name</em>' attribute.
   * @see #setService_name(String)
   * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getredeploy_Service_name()
   * @model
   * @generated
   */
  String getService_name();

  /**
   * Sets the value of the '{@link org.polarsys.chess.iot.runtimeDsl.redeploy#getService_name <em>Service name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Service name</em>' attribute.
   * @see #getService_name()
   * @generated
   */
  void setService_name(String value);

  /**
   * Returns the value of the '<em><b>Machine address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Machine address</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Machine address</em>' attribute.
   * @see #setMachine_address(String)
   * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getredeploy_Machine_address()
   * @model
   * @generated
   */
  String getMachine_address();

  /**
   * Sets the value of the '{@link org.polarsys.chess.iot.runtimeDsl.redeploy#getMachine_address <em>Machine address</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Machine address</em>' attribute.
   * @see #getMachine_address()
   * @generated
   */
  void setMachine_address(String value);

} // redeploy
