/**
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.runtimeDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>rerun Agent</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.polarsys.chess.iot.runtimeDsl.rerunAgent#getAgent <em>Agent</em>}</li>
 * </ul>
 *
 * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getrerunAgent()
 * @model
 * @generated
 */
public interface rerunAgent extends rule
{
  /**
   * Returns the value of the '<em><b>Agent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Agent</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Agent</em>' reference.
   * @see #setAgent(AbstractAgent)
   * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getrerunAgent_Agent()
   * @model
   * @generated
   */
  AbstractAgent getAgent();

  /**
   * Sets the value of the '{@link org.polarsys.chess.iot.runtimeDsl.rerunAgent#getAgent <em>Agent</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Agent</em>' reference.
   * @see #getAgent()
   * @generated
   */
  void setAgent(AbstractAgent value);

} // rerunAgent
