/**
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.runtimeDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getrule()
 * @model
 * @generated
 */
public interface rule extends EObject
{
} // rule
