/**
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.runtimeDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslFactory
 * @model kind="package"
 * @generated
 */
public interface RuntimeDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "runtimeDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.polarsys.org/chess/iot/RuntimeDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "runtimeDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RuntimeDslPackage eINSTANCE = org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.DeploymentImpl <em>Deployment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.polarsys.chess.iot.runtimeDsl.impl.DeploymentImpl
   * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getDeployment()
   * @generated
   */
  int DEPLOYMENT = 0;

  /**
   * The feature id for the '<em><b>Plan</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPLOYMENT__PLAN = 0;

  /**
   * The number of structural features of the '<em>Deployment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPLOYMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.polarsys.chess.iot.runtimeDsl.impl.ExpressionImpl
   * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__NAME = 0;

  /**
   * The feature id for the '<em><b>Setup</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__SETUP = 1;

  /**
   * The feature id for the '<em><b>Plan</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__PLAN = 2;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__DESCRIPTION = 3;

  /**
   * The feature id for the '<em><b>Agent</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__AGENT = 4;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.AbstractAgentImpl <em>Abstract Agent</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.polarsys.chess.iot.runtimeDsl.impl.AbstractAgentImpl
   * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getAbstractAgent()
   * @generated
   */
  int ABSTRACT_AGENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_AGENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_AGENT__SUPER_TYPE = 1;

  /**
   * The feature id for the '<em><b>Rule</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_AGENT__RULE = 2;

  /**
   * The number of structural features of the '<em>Abstract Agent</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_AGENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.ruleImpl <em>rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.polarsys.chess.iot.runtimeDsl.impl.ruleImpl
   * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getrule()
   * @generated
   */
  int RULE = 3;

  /**
   * The number of structural features of the '<em>rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.createImpl <em>create</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.polarsys.chess.iot.runtimeDsl.impl.createImpl
   * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getcreate()
   * @generated
   */
  int CREATE = 4;

  /**
   * The feature id for the '<em><b>Service name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE__SERVICE_NAME = RULE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Machine name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE__MACHINE_NAME = RULE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>create</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_FEATURE_COUNT = RULE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.startImpl <em>start</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.polarsys.chess.iot.runtimeDsl.impl.startImpl
   * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getstart()
   * @generated
   */
  int START = 5;

  /**
   * The feature id for the '<em><b>Service name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START__SERVICE_NAME = RULE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Machine name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START__MACHINE_NAME = RULE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>start</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_FEATURE_COUNT = RULE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.stopImpl <em>stop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.polarsys.chess.iot.runtimeDsl.impl.stopImpl
   * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getstop()
   * @generated
   */
  int STOP = 6;

  /**
   * The feature id for the '<em><b>Service name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOP__SERVICE_NAME = RULE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Machine name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOP__MACHINE_NAME = RULE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>stop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOP_FEATURE_COUNT = RULE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.restartImpl <em>restart</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.polarsys.chess.iot.runtimeDsl.impl.restartImpl
   * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getrestart()
   * @generated
   */
  int RESTART = 7;

  /**
   * The feature id for the '<em><b>Service name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTART__SERVICE_NAME = RULE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Machine name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTART__MACHINE_NAME = RULE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>restart</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTART_FEATURE_COUNT = RULE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.redeployImpl <em>redeploy</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.polarsys.chess.iot.runtimeDsl.impl.redeployImpl
   * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getredeploy()
   * @generated
   */
  int REDEPLOY = 8;

  /**
   * The feature id for the '<em><b>Service name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REDEPLOY__SERVICE_NAME = RULE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Machine address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REDEPLOY__MACHINE_ADDRESS = RULE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>redeploy</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REDEPLOY_FEATURE_COUNT = RULE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.logImpl <em>log</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.polarsys.chess.iot.runtimeDsl.impl.logImpl
   * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getlog()
   * @generated
   */
  int LOG = 9;

  /**
   * The feature id for the '<em><b>Service name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOG__SERVICE_NAME = RULE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Log type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOG__LOG_TYPE = RULE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Filename</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOG__FILENAME = RULE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOG__LOCATION = RULE_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Machine name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOG__MACHINE_NAME = RULE_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>log</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOG_FEATURE_COUNT = RULE_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.rerunAgentImpl <em>rerun Agent</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.polarsys.chess.iot.runtimeDsl.impl.rerunAgentImpl
   * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getrerunAgent()
   * @generated
   */
  int RERUN_AGENT = 10;

  /**
   * The feature id for the '<em><b>Agent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RERUN_AGENT__AGENT = RULE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>rerun Agent</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RERUN_AGENT_FEATURE_COUNT = RULE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.polarsys.chess.iot.runtimeDsl.LogType <em>Log Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.polarsys.chess.iot.runtimeDsl.LogType
   * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getLogType()
   * @generated
   */
  int LOG_TYPE = 11;

  /**
   * The meta object id for the '{@link org.polarsys.chess.iot.runtimeDsl.BOOLEAN <em>BOOLEAN</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.polarsys.chess.iot.runtimeDsl.BOOLEAN
   * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getBOOLEAN()
   * @generated
   */
  int BOOLEAN = 12;


  /**
   * Returns the meta object for class '{@link org.polarsys.chess.iot.runtimeDsl.Deployment <em>Deployment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Deployment</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.Deployment
   * @generated
   */
  EClass getDeployment();

  /**
   * Returns the meta object for the containment reference list '{@link org.polarsys.chess.iot.runtimeDsl.Deployment#getPlan <em>Plan</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Plan</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.Deployment#getPlan()
   * @see #getDeployment()
   * @generated
   */
  EReference getDeployment_Plan();

  /**
   * Returns the meta object for class '{@link org.polarsys.chess.iot.runtimeDsl.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.Expression#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.Expression#getName()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Name();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.Expression#getSetup <em>Setup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Setup</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.Expression#getSetup()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Setup();

  /**
   * Returns the meta object for the reference '{@link org.polarsys.chess.iot.runtimeDsl.Expression#getPlan <em>Plan</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Plan</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.Expression#getPlan()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Plan();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.Expression#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.Expression#getDescription()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Description();

  /**
   * Returns the meta object for the containment reference list '{@link org.polarsys.chess.iot.runtimeDsl.Expression#getAgent <em>Agent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Agent</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.Expression#getAgent()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Agent();

  /**
   * Returns the meta object for class '{@link org.polarsys.chess.iot.runtimeDsl.AbstractAgent <em>Abstract Agent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Agent</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.AbstractAgent
   * @generated
   */
  EClass getAbstractAgent();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.AbstractAgent#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.AbstractAgent#getName()
   * @see #getAbstractAgent()
   * @generated
   */
  EAttribute getAbstractAgent_Name();

  /**
   * Returns the meta object for the reference '{@link org.polarsys.chess.iot.runtimeDsl.AbstractAgent#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.AbstractAgent#getSuperType()
   * @see #getAbstractAgent()
   * @generated
   */
  EReference getAbstractAgent_SuperType();

  /**
   * Returns the meta object for the containment reference list '{@link org.polarsys.chess.iot.runtimeDsl.AbstractAgent#getRule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rule</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.AbstractAgent#getRule()
   * @see #getAbstractAgent()
   * @generated
   */
  EReference getAbstractAgent_Rule();

  /**
   * Returns the meta object for class '{@link org.polarsys.chess.iot.runtimeDsl.rule <em>rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>rule</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.rule
   * @generated
   */
  EClass getrule();

  /**
   * Returns the meta object for class '{@link org.polarsys.chess.iot.runtimeDsl.create <em>create</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>create</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.create
   * @generated
   */
  EClass getcreate();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.create#getService_name <em>Service name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Service name</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.create#getService_name()
   * @see #getcreate()
   * @generated
   */
  EAttribute getcreate_Service_name();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.create#getMachine_name <em>Machine name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Machine name</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.create#getMachine_name()
   * @see #getcreate()
   * @generated
   */
  EAttribute getcreate_Machine_name();

  /**
   * Returns the meta object for class '{@link org.polarsys.chess.iot.runtimeDsl.start <em>start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>start</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.start
   * @generated
   */
  EClass getstart();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.start#getService_name <em>Service name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Service name</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.start#getService_name()
   * @see #getstart()
   * @generated
   */
  EAttribute getstart_Service_name();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.start#getMachine_name <em>Machine name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Machine name</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.start#getMachine_name()
   * @see #getstart()
   * @generated
   */
  EAttribute getstart_Machine_name();

  /**
   * Returns the meta object for class '{@link org.polarsys.chess.iot.runtimeDsl.stop <em>stop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>stop</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.stop
   * @generated
   */
  EClass getstop();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.stop#getService_name <em>Service name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Service name</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.stop#getService_name()
   * @see #getstop()
   * @generated
   */
  EAttribute getstop_Service_name();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.stop#getMachine_name <em>Machine name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Machine name</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.stop#getMachine_name()
   * @see #getstop()
   * @generated
   */
  EAttribute getstop_Machine_name();

  /**
   * Returns the meta object for class '{@link org.polarsys.chess.iot.runtimeDsl.restart <em>restart</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>restart</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.restart
   * @generated
   */
  EClass getrestart();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.restart#getService_name <em>Service name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Service name</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.restart#getService_name()
   * @see #getrestart()
   * @generated
   */
  EAttribute getrestart_Service_name();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.restart#getMachine_name <em>Machine name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Machine name</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.restart#getMachine_name()
   * @see #getrestart()
   * @generated
   */
  EAttribute getrestart_Machine_name();

  /**
   * Returns the meta object for class '{@link org.polarsys.chess.iot.runtimeDsl.redeploy <em>redeploy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>redeploy</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.redeploy
   * @generated
   */
  EClass getredeploy();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.redeploy#getService_name <em>Service name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Service name</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.redeploy#getService_name()
   * @see #getredeploy()
   * @generated
   */
  EAttribute getredeploy_Service_name();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.redeploy#getMachine_address <em>Machine address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Machine address</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.redeploy#getMachine_address()
   * @see #getredeploy()
   * @generated
   */
  EAttribute getredeploy_Machine_address();

  /**
   * Returns the meta object for class '{@link org.polarsys.chess.iot.runtimeDsl.log <em>log</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>log</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.log
   * @generated
   */
  EClass getlog();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.log#getService_name <em>Service name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Service name</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.log#getService_name()
   * @see #getlog()
   * @generated
   */
  EAttribute getlog_Service_name();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.log#getLog_type <em>Log type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Log type</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.log#getLog_type()
   * @see #getlog()
   * @generated
   */
  EAttribute getlog_Log_type();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.log#getFilename <em>Filename</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Filename</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.log#getFilename()
   * @see #getlog()
   * @generated
   */
  EAttribute getlog_Filename();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.log#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.log#getLocation()
   * @see #getlog()
   * @generated
   */
  EAttribute getlog_Location();

  /**
   * Returns the meta object for the attribute '{@link org.polarsys.chess.iot.runtimeDsl.log#getMachine_name <em>Machine name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Machine name</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.log#getMachine_name()
   * @see #getlog()
   * @generated
   */
  EAttribute getlog_Machine_name();

  /**
   * Returns the meta object for class '{@link org.polarsys.chess.iot.runtimeDsl.rerunAgent <em>rerun Agent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>rerun Agent</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.rerunAgent
   * @generated
   */
  EClass getrerunAgent();

  /**
   * Returns the meta object for the reference '{@link org.polarsys.chess.iot.runtimeDsl.rerunAgent#getAgent <em>Agent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Agent</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.rerunAgent#getAgent()
   * @see #getrerunAgent()
   * @generated
   */
  EReference getrerunAgent_Agent();

  /**
   * Returns the meta object for enum '{@link org.polarsys.chess.iot.runtimeDsl.LogType <em>Log Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Log Type</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.LogType
   * @generated
   */
  EEnum getLogType();

  /**
   * Returns the meta object for enum '{@link org.polarsys.chess.iot.runtimeDsl.BOOLEAN <em>BOOLEAN</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>BOOLEAN</em>'.
   * @see org.polarsys.chess.iot.runtimeDsl.BOOLEAN
   * @generated
   */
  EEnum getBOOLEAN();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RuntimeDslFactory getRuntimeDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.DeploymentImpl <em>Deployment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.polarsys.chess.iot.runtimeDsl.impl.DeploymentImpl
     * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getDeployment()
     * @generated
     */
    EClass DEPLOYMENT = eINSTANCE.getDeployment();

    /**
     * The meta object literal for the '<em><b>Plan</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPLOYMENT__PLAN = eINSTANCE.getDeployment_Plan();

    /**
     * The meta object literal for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.polarsys.chess.iot.runtimeDsl.impl.ExpressionImpl
     * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__NAME = eINSTANCE.getExpression_Name();

    /**
     * The meta object literal for the '<em><b>Setup</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__SETUP = eINSTANCE.getExpression_Setup();

    /**
     * The meta object literal for the '<em><b>Plan</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__PLAN = eINSTANCE.getExpression_Plan();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__DESCRIPTION = eINSTANCE.getExpression_Description();

    /**
     * The meta object literal for the '<em><b>Agent</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__AGENT = eINSTANCE.getExpression_Agent();

    /**
     * The meta object literal for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.AbstractAgentImpl <em>Abstract Agent</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.polarsys.chess.iot.runtimeDsl.impl.AbstractAgentImpl
     * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getAbstractAgent()
     * @generated
     */
    EClass ABSTRACT_AGENT = eINSTANCE.getAbstractAgent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSTRACT_AGENT__NAME = eINSTANCE.getAbstractAgent_Name();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABSTRACT_AGENT__SUPER_TYPE = eINSTANCE.getAbstractAgent_SuperType();

    /**
     * The meta object literal for the '<em><b>Rule</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABSTRACT_AGENT__RULE = eINSTANCE.getAbstractAgent_Rule();

    /**
     * The meta object literal for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.ruleImpl <em>rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.polarsys.chess.iot.runtimeDsl.impl.ruleImpl
     * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getrule()
     * @generated
     */
    EClass RULE = eINSTANCE.getrule();

    /**
     * The meta object literal for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.createImpl <em>create</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.polarsys.chess.iot.runtimeDsl.impl.createImpl
     * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getcreate()
     * @generated
     */
    EClass CREATE = eINSTANCE.getcreate();

    /**
     * The meta object literal for the '<em><b>Service name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CREATE__SERVICE_NAME = eINSTANCE.getcreate_Service_name();

    /**
     * The meta object literal for the '<em><b>Machine name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CREATE__MACHINE_NAME = eINSTANCE.getcreate_Machine_name();

    /**
     * The meta object literal for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.startImpl <em>start</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.polarsys.chess.iot.runtimeDsl.impl.startImpl
     * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getstart()
     * @generated
     */
    EClass START = eINSTANCE.getstart();

    /**
     * The meta object literal for the '<em><b>Service name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute START__SERVICE_NAME = eINSTANCE.getstart_Service_name();

    /**
     * The meta object literal for the '<em><b>Machine name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute START__MACHINE_NAME = eINSTANCE.getstart_Machine_name();

    /**
     * The meta object literal for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.stopImpl <em>stop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.polarsys.chess.iot.runtimeDsl.impl.stopImpl
     * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getstop()
     * @generated
     */
    EClass STOP = eINSTANCE.getstop();

    /**
     * The meta object literal for the '<em><b>Service name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STOP__SERVICE_NAME = eINSTANCE.getstop_Service_name();

    /**
     * The meta object literal for the '<em><b>Machine name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STOP__MACHINE_NAME = eINSTANCE.getstop_Machine_name();

    /**
     * The meta object literal for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.restartImpl <em>restart</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.polarsys.chess.iot.runtimeDsl.impl.restartImpl
     * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getrestart()
     * @generated
     */
    EClass RESTART = eINSTANCE.getrestart();

    /**
     * The meta object literal for the '<em><b>Service name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESTART__SERVICE_NAME = eINSTANCE.getrestart_Service_name();

    /**
     * The meta object literal for the '<em><b>Machine name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESTART__MACHINE_NAME = eINSTANCE.getrestart_Machine_name();

    /**
     * The meta object literal for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.redeployImpl <em>redeploy</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.polarsys.chess.iot.runtimeDsl.impl.redeployImpl
     * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getredeploy()
     * @generated
     */
    EClass REDEPLOY = eINSTANCE.getredeploy();

    /**
     * The meta object literal for the '<em><b>Service name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REDEPLOY__SERVICE_NAME = eINSTANCE.getredeploy_Service_name();

    /**
     * The meta object literal for the '<em><b>Machine address</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REDEPLOY__MACHINE_ADDRESS = eINSTANCE.getredeploy_Machine_address();

    /**
     * The meta object literal for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.logImpl <em>log</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.polarsys.chess.iot.runtimeDsl.impl.logImpl
     * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getlog()
     * @generated
     */
    EClass LOG = eINSTANCE.getlog();

    /**
     * The meta object literal for the '<em><b>Service name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOG__SERVICE_NAME = eINSTANCE.getlog_Service_name();

    /**
     * The meta object literal for the '<em><b>Log type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOG__LOG_TYPE = eINSTANCE.getlog_Log_type();

    /**
     * The meta object literal for the '<em><b>Filename</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOG__FILENAME = eINSTANCE.getlog_Filename();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOG__LOCATION = eINSTANCE.getlog_Location();

    /**
     * The meta object literal for the '<em><b>Machine name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOG__MACHINE_NAME = eINSTANCE.getlog_Machine_name();

    /**
     * The meta object literal for the '{@link org.polarsys.chess.iot.runtimeDsl.impl.rerunAgentImpl <em>rerun Agent</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.polarsys.chess.iot.runtimeDsl.impl.rerunAgentImpl
     * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getrerunAgent()
     * @generated
     */
    EClass RERUN_AGENT = eINSTANCE.getrerunAgent();

    /**
     * The meta object literal for the '<em><b>Agent</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RERUN_AGENT__AGENT = eINSTANCE.getrerunAgent_Agent();

    /**
     * The meta object literal for the '{@link org.polarsys.chess.iot.runtimeDsl.LogType <em>Log Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.polarsys.chess.iot.runtimeDsl.LogType
     * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getLogType()
     * @generated
     */
    EEnum LOG_TYPE = eINSTANCE.getLogType();

    /**
     * The meta object literal for the '{@link org.polarsys.chess.iot.runtimeDsl.BOOLEAN <em>BOOLEAN</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.polarsys.chess.iot.runtimeDsl.BOOLEAN
     * @see org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslPackageImpl#getBOOLEAN()
     * @generated
     */
    EEnum BOOLEAN = eINSTANCE.getBOOLEAN();

  }

} //RuntimeDslPackage
