/**
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.runtimeDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage
 * @generated
 */
public interface RuntimeDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RuntimeDslFactory eINSTANCE = org.polarsys.chess.iot.runtimeDsl.impl.RuntimeDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Deployment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Deployment</em>'.
   * @generated
   */
  Deployment createDeployment();

  /**
   * Returns a new object of class '<em>Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expression</em>'.
   * @generated
   */
  Expression createExpression();

  /**
   * Returns a new object of class '<em>Abstract Agent</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Agent</em>'.
   * @generated
   */
  AbstractAgent createAbstractAgent();

  /**
   * Returns a new object of class '<em>rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>rule</em>'.
   * @generated
   */
  rule createrule();

  /**
   * Returns a new object of class '<em>create</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>create</em>'.
   * @generated
   */
  create createcreate();

  /**
   * Returns a new object of class '<em>start</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>start</em>'.
   * @generated
   */
  start createstart();

  /**
   * Returns a new object of class '<em>stop</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>stop</em>'.
   * @generated
   */
  stop createstop();

  /**
   * Returns a new object of class '<em>restart</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>restart</em>'.
   * @generated
   */
  restart createrestart();

  /**
   * Returns a new object of class '<em>redeploy</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>redeploy</em>'.
   * @generated
   */
  redeploy createredeploy();

  /**
   * Returns a new object of class '<em>log</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>log</em>'.
   * @generated
   */
  log createlog();

  /**
   * Returns a new object of class '<em>rerun Agent</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>rerun Agent</em>'.
   * @generated
   */
  rerunAgent creatererunAgent();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  RuntimeDslPackage getRuntimeDslPackage();

} //RuntimeDslFactory
