/**
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.runtimeDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>stop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.polarsys.chess.iot.runtimeDsl.stop#getService_name <em>Service name</em>}</li>
 *   <li>{@link org.polarsys.chess.iot.runtimeDsl.stop#getMachine_name <em>Machine name</em>}</li>
 * </ul>
 *
 * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getstop()
 * @model
 * @generated
 */
public interface stop extends rule
{
  /**
   * Returns the value of the '<em><b>Service name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Service name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Service name</em>' attribute.
   * @see #setService_name(String)
   * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getstop_Service_name()
   * @model
   * @generated
   */
  String getService_name();

  /**
   * Sets the value of the '{@link org.polarsys.chess.iot.runtimeDsl.stop#getService_name <em>Service name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Service name</em>' attribute.
   * @see #getService_name()
   * @generated
   */
  void setService_name(String value);

  /**
   * Returns the value of the '<em><b>Machine name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Machine name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Machine name</em>' attribute.
   * @see #setMachine_name(String)
   * @see org.polarsys.chess.iot.runtimeDsl.RuntimeDslPackage#getstop_Machine_name()
   * @model
   * @generated
   */
  String getMachine_name();

  /**
   * Sets the value of the '{@link org.polarsys.chess.iot.runtimeDsl.stop#getMachine_name <em>Machine name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Machine name</em>' attribute.
   * @see #getMachine_name()
   * @generated
   */
  void setMachine_name(String value);

} // stop
