/*
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRuntimeDslScopeProvider extends DelegatingScopeProvider {
}
