<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fmea" nsURI="http://www.polarsys.org/chess/mbsanice/fmea" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="Row">
    <eStructuralFeatures xsi:type="ecore:EReference" name="localPort" eType="ecore:EClass ../../org.polarsys.chess.fla.flamm/model/flamm.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="failureMode" upperBound="-1"
        eType="ecore:EClass ../../org.polarsys.chess.fla.flamm/model/flamm.ecore#//Rule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localEffect" eType="ecore:EClass ../../org.polarsys.chess.fla.flamm/model/flamm.ecore#//Failure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endPort" eType="ecore:EClass ../../org.polarsys.chess.fla.flamm/model/flamm.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endEffect" eType="ecore:EClass ../../org.polarsys.chess.fla.flamm/model/flamm.ecore#//Failure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interPorts" upperBound="-1"
        eType="#//InterPort" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterPort">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="ecore:EClass ../../org.polarsys.chess.fla.flamm/model/flamm.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="failure" eType="ecore:EClass ../../org.polarsys.chess.fla.flamm/model/flamm.ecore#//Failure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fmea">
    <eStructuralFeatures xsi:type="ecore:EReference" name="row" upperBound="-1" eType="#//Row"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
