/**
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.polarsys.chess.iot.ui.AbstractRuntimeDslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RuntimeDslUiModule extends AbstractRuntimeDslUiModule {
  public RuntimeDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
