/*
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.polarsys.chess.iot.parser.antlr.internal.InternalRuntimeDslParser;
import org.polarsys.chess.iot.services.RuntimeDslGrammarAccess;

public class RuntimeDslParser extends AbstractAntlrParser {

	@Inject
	private RuntimeDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRuntimeDslParser createParser(XtextTokenStream stream) {
		return new InternalRuntimeDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public RuntimeDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RuntimeDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
