/*
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RuntimeDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/polarsys/chess/iot/parser/antlr/internal/InternalRuntimeDsl.tokens");
	}
}
