/**
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.polarsys.chess.iot.RuntimeDslRuntimeModule;
import org.polarsys.chess.iot.RuntimeDslStandaloneSetup;
import org.polarsys.chess.iot.ide.RuntimeDslIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RuntimeDslIdeSetup extends RuntimeDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    RuntimeDslRuntimeModule _runtimeDslRuntimeModule = new RuntimeDslRuntimeModule();
    RuntimeDslIdeModule _runtimeDslIdeModule = new RuntimeDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_runtimeDslRuntimeModule, _runtimeDslIdeModule));
  }
}
