/**
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.ide;

import org.polarsys.chess.iot.ide.AbstractRuntimeDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RuntimeDslIdeModule extends AbstractRuntimeDslIdeModule {
}
