/*
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link RuntimeDslWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractRuntimeDslWebModule extends DefaultWebModule {

}
