/*
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.polarsys.chess.iot.runtimedsl.ui.internal.RuntimedslActivator;

public class RuntimeDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RuntimedslActivator.getInstance().getInjector("org.polarsys.chess.iot.RuntimeDsl");
	}

}
