<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CHESSIoT" nsURI="http:///CHESSIoT.ecore" nsPrefix="chessiot">
  <eSubpackages name="CHESSIoTSoftware" nsURI="http:///CHESSIoT/CHESSIoTSoftware.ecore"
      nsPrefix="CHESSIoT.CHESSIoTSoftware">
    <eClassifiers xsi:type="ecore:EClass" name="VirtualEntity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="virtualentity" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSoftware/VirtualEntity"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
          eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VirtualElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
          eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="virtualelement" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSoftware/VirtualElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="virtualentity" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSoftware/VirtualEntity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iotport" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//CHESSIoTSoftware/IoTPort"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iotstate" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSoftware/StateMachine" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IoTPort">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Port" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Port"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pin" ordered="false"
          upperBound="-1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sends" ordered="false"
          upperBound="-1" eType="#//CHESSIoTSoftware/Payload"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="receives" ordered="false"
          upperBound="-1" eType="#//CHESSIoTSoftware/Payload"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Payload">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="have" ordered="false"
          upperBound="-1" eType="#//CHESSIoTSoftware/MessageParameters" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="payloadType" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSoftware/PayloadType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MessageParameters">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PayloadType">
      <eLiterals name="TEXT"/>
      <eLiterals name="BINARY" value="1"/>
      <eLiterals name="IMAGE" value="2"/>
      <eLiterals name="OTHER" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
      <eStructuralFeatures xsi:type="ecore:EReference" name="region" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSoftware/Region" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_StateMachine" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//StateMachine"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Region">
      <eStructuralFeatures xsi:type="ecore:EReference" name="iotstate" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSoftware/IoTState"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Region" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Region"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IoTState">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_State" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//State"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iotevent" ordered="false"
          upperBound="-1" eType="#//CHESSIoTSoftware/IoTEvent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IoTEvent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IncomingEvent" eSuperTypes="#//CHESSIoTSoftware/IoTEvent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="receivepayload" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSoftware/ReceivePayload"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingevent" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSoftware/OutgoingEvent" eOpposite="#//CHESSIoTSoftware/OutgoingEvent/incomingevent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReceivePayload" eSuperTypes="#//CHESSIoTSoftware/IoTAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="iotport" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSoftware/IoTPort"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="payload" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSoftware/Payload"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IoTAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OutgoingEvent" eSuperTypes="#//CHESSIoTSoftware/IoTEvent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPeriodic" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeInterval" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sendpayload" ordered="false"
          upperBound="-1" eType="#//CHESSIoTSoftware/SendPayload"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingevent" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSoftware/IncomingEvent" eOpposite="#//CHESSIoTSoftware/IncomingEvent/outgoingevent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SendPayload" eSuperTypes="#//CHESSIoTSoftware/IoTAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="payload" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//CHESSIoTSoftware/Payload"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iotport" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSoftware/IoTPort"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StateTransition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Transition" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Transition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iotstate" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSoftware/IoTState"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GenericEvent" eSuperTypes="#//CHESSIoTSoftware/IoTEvent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPeriodic" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeInterval" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GenericIoTAction" eSuperTypes="#//CHESSIoTSoftware/IoTAction">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionName" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionType" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSoftware/GenericActIoType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="GenericActIoType">
      <eLiterals name="EXTERNAL"/>
      <eLiterals name="LOOP" value="1"/>
      <eLiterals name="CONDITION" value="2"/>
      <eLiterals name="ASSIGNMENT" value="3"/>
      <eLiterals name="RETURN" value="4"/>
      <eLiterals name="ERROR" value="5"/>
      <eLiterals name="PRINT" value="6"/>
      <eLiterals name="FUNCTION_CALL" value="7"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VitualComputingNode" eSuperTypes="#//CHESSIoTSoftware/VirtualElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" ordered="false"
          upperBound="-1" eType="#//CHESSIoTSoftware/Sensor" eOpposite="#//CHESSIoTSoftware/Sensor/computingnode"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actuator" ordered="false"
          upperBound="-1" eType="#//CHESSIoTSoftware/Actuator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="#//CHESSIoTSoftware/VirtualElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="computingnode" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSoftware/VitualComputingNode" eOpposite="#//CHESSIoTSoftware/VitualComputingNode/sensor"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Actuator" eSuperTypes="#//CHESSIoTSoftware/VirtualElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="SYSTEM">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="virtualentity" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSoftware/VirtualEntity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="CHESSIoTOperationalProfile" nsURI="http:///CHESSIoT/CHESSIoTOperationalProfile.ecore"
      nsPrefix="CHESSIoT.CHESSIoTOperationalProfile">
    <eClassifiers xsi:type="ecore:EClass" name="Service">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceName" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resource" ordered="false"
          lowerBound="1" eType="#//CHESSIoTOperationalProfile/Resource"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="api" ordered="false"
          lowerBound="1" eType="#//CHESSIoTOperationalProfile/API" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Resource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessPoint" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="API"/>
    <eClassifiers xsi:type="ecore:EClass" name="CloudServer" eSuperTypes="#//CHESSIoTOperationalProfile/Node">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="networkresources" ordered="false"
          lowerBound="1" eType="#//CHESSIoTOperationalProfile/NetworkResources" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Node">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resource" ordered="false"
          lowerBound="1" eType="#//CHESSIoTOperationalProfile/DeviceResources" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="memory" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="node" ordered="false"
          lowerBound="1" eType="#//CHESSIoTOperationalProfile/Node"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeviceResources" eSuperTypes="#//CHESSIoTOperationalProfile/Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="NetworkResources" eSuperTypes="#//CHESSIoTOperationalProfile/Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="Application">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resource" ordered="false"
          lowerBound="1" eType="#//CHESSIoTOperationalProfile/Service"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="api" ordered="false"
          lowerBound="1" eType="#//CHESSIoTOperationalProfile/API" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="User">
      <eStructuralFeatures xsi:type="ecore:EReference" name="application" ordered="false"
          lowerBound="1" eType="#//CHESSIoTOperationalProfile/Application"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="CHESSIoTSystem" nsURI="http:///CHESSIoT/CHESSIoTSystem.ecore"
      nsPrefix="CHESSIoT.CHESSIoTSystem">
    <eClassifiers xsi:type="ecore:EClass" name="ComputingBoard" eSuperTypes="#//CHESSIoTSystem/PhysicalElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nodeModel" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/NodeModel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="gateway" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/Gateway" eOpposite="#//CHESSIoTSystem/Gateway/computingboard"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actuatingblock" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/ActuatingBlock"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sensorblock" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/SensorBlock" eOpposite="#//CHESSIoTSystem/SensorBlock/computingboard"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="physicalentity" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/PhysicalEntity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PhysicalElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitude" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitude" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Block" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.papyrus.sysml/model/sysml.ecore#//blocks/Block"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iotport" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/IoTPort" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IoTPort" eSuperTypes="../org.eclipse.papyrus.sysml/model/sysml.ecore#//portandflows/FlowPort"/>
    <eClassifiers xsi:type="ecore:EEnum" name="NodeModel">
      <eLiterals name="RasberryPi"/>
      <eLiterals name="Arduino" value="1"/>
      <eLiterals name="Teensy" value="2"/>
      <eLiterals name="BeagleBoneBlack" value="3"/>
      <eLiterals name="Adafruit" value="4"/>
      <eLiterals name="OTHER" value="5"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Gateway" eSuperTypes="#//CHESSIoTSystem/PhysicalElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="gateway" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/Gateway"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="server" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/Server"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="computingboard" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/ComputingBoard" eOpposite="#//CHESSIoTSystem/ComputingBoard/gateway"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Server" eSuperTypes="../org.eclipse.papyrus.sysml/model/sysml.ecore#//blocks/Block">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="opSystem" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iotport" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/IoTPort"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActuatingBlock" eSuperTypes="#//CHESSIoTSystem/PhysicalElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="actuationType" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/ActuatorType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="physicalentity" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/PhysicalEntity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ActuatorType">
      <eLiterals name="LED"/>
      <eLiterals name="BUZZER" value="1"/>
      <eLiterals name="SERVO" value="2"/>
      <eLiterals name="OTHER" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PhysicalEntity" eSuperTypes="#//CHESSIoTSystem/PhysicalElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
          eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="physicalentity" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/PhysicalEntity" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SensorBlock" eSuperTypes="#//CHESSIoTSystem/PhysicalElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensorType" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/SensorType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="physicalentity" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/PhysicalEntity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="computingboard" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/ComputingBoard" eOpposite="#//CHESSIoTSystem/ComputingBoard/sensorblock"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SensorType">
      <eLiterals name="HUMIDITY"/>
      <eLiterals name="TEMPERATURE" value="1"/>
      <eLiterals name="GAZ" value="2"/>
      <eLiterals name="MOTION" value="3"/>
      <eLiterals name="ULTRASONIC" value="4"/>
      <eLiterals name="OTHER" value="5"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CommunicationMode">
      <eLiterals name="WIRELESS"/>
      <eLiterals name="WIRED" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Connection">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="commMode" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/CommunicationMode"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Connector" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Connector"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iotport" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/IoTPort"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SYSTEM_Hw">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Block" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.papyrus.sysml/model/sysml.ecore#//blocks/Block"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="physicalentity" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/PhysicalEntity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iotport" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/IoTPort" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="server" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/Server" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="system_hw" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/SYSTEM_Hw" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="physicalelement" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/PhysicalElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConsumerEntity" eSuperTypes="../org.eclipse.papyrus.sysml/model/sysml.ecore#//blocks/Block"/>
    <eClassifiers xsi:type="ecore:EClass" name="Active" eSuperTypes="#//CHESSIoTSystem/ConsumerEntity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="server" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/Server"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Passive" eSuperTypes="#//CHESSIoTSystem/ConsumerEntity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="physicalentity" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSystem/PhysicalEntity"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="CHESSIoTDeployment" nsURI="http:///CHESSIoT/CHESSIoTDeployment.ecore"
      nsPrefix="CHESSIoT.CHESSIoTDeployment">
    <eClassifiers xsi:type="ecore:EEnum" name="PortType">
      <eLiterals name="ANALOG"/>
      <eLiterals name="DIGITAL" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SensorType">
      <eLiterals name="Humidity"/>
      <eLiterals name="Temeperature" value="1"/>
      <eLiterals name="Gaz" value="2"/>
      <eLiterals name="Ultrasonic" value="3"/>
      <eLiterals name="Body" value="4"/>
      <eLiterals name="Undefined" value="5"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ActuatorType">
      <eLiterals name="Servo"/>
      <eLiterals name="Relay" value="1"/>
      <eLiterals name="Sonore" value="2"/>
      <eLiterals name="Led" value="3"/>
      <eLiterals name="Undefined" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SensorUnit">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensorType" ordered="false"
          lowerBound="1" eType="#//CHESSIoTDeployment/SensorType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActuatorUnit">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="actuatorType" ordered="false"
          lowerBound="1" eType="#//CHESSIoTDeployment/ActuatorType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PhysicalBaord">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="boardName" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="virtualBoard" ordered="false"
          lowerBound="1" eType="#//CHESSIoTSoftware/VitualComputingNode"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SystemHW">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="portIn" eSuperTypes="#//CHESSIoTDeployment/IoTPort"/>
    <eClassifiers xsi:type="ecore:EClass" name="IoTPort">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false"
          lowerBound="1" eType="#//CHESSIoTDeployment/PortType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="aaportName" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Port" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Port"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="portOut" eSuperTypes="#//CHESSIoTDeployment/IoTPort"/>
    <eClassifiers xsi:type="ecore:EClass" name="TagUnit">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
          lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
