/*
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.ide.contentassist.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;
import org.polarsys.chess.iot.ide.contentassist.antlr.internal.InternalRuntimeDslParser;

public class RuntimeDslTokenSource extends AbstractIndentationTokenSource {

	public RuntimeDslTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalRuntimeDslParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalRuntimeDslParser.RULE_ANY_OTHER;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalRuntimeDslParser.RULE_ANY_OTHER;
	}

	@Override
	protected boolean shouldEmitPendingEndTokens() {
		return false;
	}
}
