/*
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.polarsys.chess.iot.runtimedsl.ui.internal.RuntimedslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RuntimeDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RuntimedslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RuntimedslActivator.getInstance().getInjector(RuntimedslActivator.ORG_POLARSYS_CHESS_IOT_RUNTIMEDSL);
	}
	
}
