/*
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RuntimeDslStandaloneSetup extends RuntimeDslStandaloneSetupGenerated {

	def static void doSetup() {
		new RuntimeDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
