/**
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.web;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class RuntimeDslWebSetup /* implements RuntimeDslStandaloneSetup  */{
  @Override
  public /* Injector */Object createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Guice is undefined"
      + "\nThe method or field Modules2 is undefined"
      + "\nRuntimeDslRuntimeModule cannot be resolved."
      + "\nRuntimeDslIdeModule cannot be resolved."
      + "\ncreateInjector cannot be resolved"
      + "\nmixin cannot be resolved");
  }
}
