/**
 * generated by Xtext 2.12.0
 */
package org.polarsys.chess.iot.web;

import org.polarsys.chess.iot.web.AbstractRuntimeDslWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class RuntimeDslWebModule extends AbstractRuntimeDslWebModule {
}
